export const posts = [
  {
    id: 7,
    title: "Thai Curry",
    content: ["Green Curry", "Red Curry", "Massaman"],
    category: "American",
    price: 16.99,
  },
  {
    id: 3,
    title: "Mexican Tacos",
    content: ["Authentic Street Tacos"],
    category: "Mexican",
    price: 9.99,
  },
  {
    id: 10,
    title: "Vietnamese Pho",
    content: ["Traditional Beef Pho"],
    category: "American",
    price: 13.99,
  },
  {
    id: 5,
    title: "Japanese Sushi",
    content: ["California Roll", "Dragon Roll", "Tempura"],
    category: "Mexican",
    price: 22.99,
  },
  {
    id: 8,
    title: "American Burger",
    content: ["Classic Cheeseburger"],
    category: "American",
    price: 11.99,
  },
  {
    id: 2,
    title: "Chinese Cuisine",
    content: ["Noodles", "Dumplings", "Fried Rice"],
    category: "Italian",
    price: 15.99,
  },
  {
    id: 6,
    title: "Greek Salad",
    content: ["Mediterranean Fresh Salad"],
    category: "Italian",
    price: 8.99,
  },
  {
    id: 1,
    title: "Italian Pasta",
    content: ["Spaghetti", "Penne", "Fettuccine"],
    category: "Italian",
    price: 12.99,
  },
  {
    id: 9,
    title: "French Pastries",
    content: ["Croissant", "Éclair", "Macaron"],
    category: "French",
    price: 18.99,
  },
  {
    id: 4,
    title: "Indian Curry",
    content: ["Butter Chicken", "Tikka Masala", "Biryani"],
    category: "Mexican",
    price: 14.99,
  },
  {
    id: 11,
    title: "Spanish Paella",
    content: ["Seafood Paella"],
    category: "Spanish",
    price: 19.99,
  },
  {
    id: 12,
    title: "German Bratwurst",
    content: ["Traditional Bratwurst"],
    category: "German",
    price: 10.99,
  },
  {
    id: 13,
    title: "Brazilian Feijoada",
    content: ["Black Bean Stew"],
    category: "Brazilian",
    price: 17.99,
  },
  {
    id: 14,
    title: "Korean BBQ",
    content: ["Bulgogi", "Galbi"],
    category: "Korean",
    price: 21.99,
  },
  {
    id: 15,
    title: "Turkish Kebab",
    content: ["Doner Kebab"],
    category: "Turkish",
    price: 13.99,
  },
  {
    id: 16,
    title: "Russian Borscht",
    content: ["Beet Soup"],
    category: "Russian",
    price: 9.99,
  },
  {
    id: 17,
    title: "Moroccan Tagine",
    content: ["Lamb Tagine"],
    category: "Moroccan",
    price: 18.99,
  },
  {
    id: 18,
    title: "Ethiopian Injera",
    content: ["Sourdough Flatbread"],
    category: "Ethiopian",
    price: 11.99,
  },
  {
    id: 19,
    title: "Lebanese Mezze",
    content: ["Hummus", "Tabbouleh"],
    category: "Lebanese",
    price: 14.99,
  },
  {
    id: 20,
    title: "Argentinian Asado",
    content: ["Grilled Meats"],
    category: "Argentinian",
    price: 23.99,
  },
  {
    id: 21,
    title: "Peruvian Ceviche",
    content: ["Fish Ceviche"],
    category: "Peruvian",
    price: 15.99,
  },
  {
    id: 22,
    title: "Egyptian Koshari",
    content: ["Lentils and Rice"],
    category: "Egyptian",
    price: 8.99,
  },
  {
    id: 23,
    title: "Indonesian Satay",
    content: ["Chicken Satay"],
    category: "Indonesian",
    price: 12.99,
  },
  {
    id: 24,
    title: "Thai Pad Thai",
    content: ["Stir-Fried Noodles"],
    category: "Thai",
    price: 13.99,
  },
  {
    id: 25,
    title: "Italian Risotto",
    content: ["Mushroom Risotto"],
    category: "Italian",
    price: 16.99,
  },
  {
    id: 26,
    title: "French Ratatouille",
    content: ["Vegetable Stew"],
    category: "French",
    price: 14.99,
  },
  {
    id: 27,
    title: "Japanese Ramen",
    content: ["Tonkotsu Ramen"],
    category: "Japanese",
    price: 11.99,
  },
  {
    id: 28,
    title: "Mexican Enchiladas",
    content: ["Chicken Enchiladas"],
    category: "Mexican",
    price: 10.99,
  },
  {
    id: 29,
    title: "Indian Samosa",
    content: ["Potato Samosa"],
    category: "Indian",
    price: 7.99,
  },
  {
    id: 30,
    title: "Chinese Dim Sum",
    content: ["Pork Dumplings"],
    category: "Chinese",
    price: 12.99,
  },
  {
    id: 31,
    title: "Vietnamese Banh Mi",
    content: ["Pork Sandwich"],
    category: "Vietnamese",
    price: 9.99,
  },
  {
    id: 32,
    title: "Greek Moussaka",
    content: ["Eggplant Casserole"],
    category: "Greek",
    price: 15.99,
  },
  {
    id: 33,
    title: "Turkish Baklava",
    content: ["Sweet Pastry"],
    category: "Turkish",
    price: 8.99,
  },
  {
    id: 34,
    title: "Moroccan Couscous",
    content: ["Vegetable Couscous"],
    category: "Moroccan",
    price: 13.99,
  },
  {
    id: 35,
    title: "Spanish Churros",
    content: ["Fried Dough"],
    category: "Spanish",
    price: 6.99,
  },
  {
    id: 36,
    title: "Korean Kimchi",
    content: ["Fermented Vegetables"],
    category: "Korean",
    price: 5.99,
  },
  {
    id: 37,
    title: "Brazilian Brigadeiro",
    content: ["Chocolate Truffle"],
    category: "Brazilian",
    price: 4.99,
  },
  {
    id: 38,
    title: "German Pretzel",
    content: ["Salted Bread"],
    category: "German",
    price: 3.99,
  },
  {
    id: 39,
    title: "Ethiopian Doro Wat",
    content: ["Spicy Chicken Stew"],
    category: "Ethiopian",
    price: 14.99,
  },
  {
    id: 40,
    title: "Lebanese Falafel",
    content: ["Chickpea Fritters"],
    category: "Lebanese",
    price: 9.99,
  }
];

// Shuffle the array to jumble the entries
export const shuffledPosts = posts.sort((a,b) => a.id-b.id);